config/routes.rb
Rails.application.routes.draw do
  resources :work_types
  root :to => "catalog#index"
  blacklight_for :catalog
  devise_for :users, skip: [:sessions], controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  mount Hydra::Collections::Engine => '/'
  mount Worthwhile::Engine, at: '/'
  worthwhile_collections
  worthwhile_curation_concerns
  worthwhile_embargo_management

end

app/controllers/work_types_controller.rb
class WorkTypesController < ApplicationController
  before_action :set_work_type, only: [:show, :edit, :update, :destroy]

  # GET /work_types
  # GET /work_types.json
  def index
    @work_types = WorkType.all
  end

  # GET /work_types/1
  # GET /work_types/1.json
  def show
  end

  # GET /work_types/new
  def new
    @work_type = WorkType.new
  end

  # GET /work_types/1/edit
  def edit
  end

  # POST /work_types
  # POST /work_types.json
  def create
    @work_type = WorkType.new(work_type_params)

    respond_to do |format|
      if @work_type.save
        format.html { redirect_to @work_type, notice: 'Work type was successfully created.' }
        format.json { render :show, status: :created, location: @work_type }
      else
        format.html { render :new }
        format.json { render json: @work_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_types/1
  # PATCH/PUT /work_types/1.json
  def update
    respond_to do |format|
      if @work_type.update(work_type_params)
        activate_schema
        format.html { redirect_to @work_type, notice: 'Work type was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_type }
      else
        format.html { render :edit }
        format.json { render json: @work_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_types/1
  # DELETE /work_types/1.json
  def destroy
    @work_type.destroy
    respond_to do |format|
      format.html { redirect_to work_types_url, notice: 'Work type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_type
      @work_type = WorkType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_type_params
      params.require(:work_type).permit(:registered_name, :display_name, :is_type_of, :schema_file)
    end

    def activate_schema
      if @work_type.schema_datastream
        schema_file = @work_type.schema_datastream
        file_name = @work_type.registered_name.underscore + '.yml'
        begin
          puts "Updating the schema file in config/work_types/#{file_name} from Work Type in Fedora"
          File.open(Rails.root + "config/work_types/" + file_name, "w+b") {|f| f.write(schema_file.read)}
        rescue
          puts "Unable to write new config to config/work_types/#{file_name}"
        end
      end
    end

end

app/views/work_types/_form.html.erb
<%= form_for(@work_type) do |f| %>
  <% if @work_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_type.errors.count, "error") %> prohibited this work_type from being saved:</h2>

      <ul>
      <% @work_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :registered_name %><br>
    <%= f.text_field :registered_name %>
  </div>
  <div class="field">
    <%= f.label :display_name %><br>
    <%= f.text_field :display_name %>
  </div>
  <div class="field">
    <%= f.label :is_type_of %><br>
    <%= f.text_field :is_type_of %>
  </div>

  <ul>
   <% if !@work_type.new? %>
      <li class='field'>
        <span class="form_label">Current Schema File</span>
        <span class="form_field">
        <% if @work_type.schema_datastream.has_content? %>
          <%= link_to @work_type.schema_datastream.dsid, ActiveFedora.fedora_config.credentials[:url] + '/' + @work_type.schema_datastream.url %>
        <% else %>
          none.
        <% end %>
        </span>
      </li>
    <% end %>
    
    <li class='field'>
      <%= f.label 'Select new Schema File' %>
      <%= f.file_field :schema_file %>
    </li>
  </ul>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_types/edit.html.erb
<h1>Editing Work Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_type %> |
<%= link_to 'Back', work_types_path %>

app/views/work_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Work Types Manager</h1>

<table>
  <thead>
    <tr>
      <th>Name </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @work_types.each do |work_type| %>
      <tr>
        <td><%= work_type.display_name %></td>
        <td><%= link_to 'Show', work_type %></td>
        <td><%= link_to 'Edit', edit_work_type_path(work_type) %></td>
        <td><%= link_to 'Destroy', work_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work type', new_work_type_path %>

app/views/work_types/new.html.erb
<h1>New Work Type</h1>

<%= render 'form' %>

<%= link_to 'Back', work_types_path %>

app/views/work_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Registered Name:</strong>
  <%= @work_type.registered_name %>
</p>

<p>
  <strong>Display Name:</strong>
  <%= @work_type.display_name %>
</p>

<p>
  <strong>Is Type Of:</strong>
  <%= @work_type.is_type_of %>
</p>

<p>
  <strong>Schema File:</strong>
     <% if @work_type.schema_file.has_content? %>
       <%= link_to @work_type.schema_datastream.dsid,
                  ActiveFedora.fedora_config.credentials[:url] +
                    '/' + @work_type.schema_datastream.url %>
     <% else %>
       none.
     <% end %>
</p>


<%= link_to 'Edit', edit_work_type_path(@work_type) %> |
<%= link_to 'Back', work_types_path %>